import '../../styles/mowgle88/style.css';
import '../components/methods/call-api';
import '../components/methods/get-words';
import '../components/methods/get-word';
// import '../components/methods/create-user';
// import '../components/methods/sign-in';
// import '../components/methods/get-user';
// import '../components/methods/update-user';
// import '../components/methods/delete-user';
// import '../components/methods/get-user-tokens';
import '../mowgle88/sprint/sprint-page';
import '../mowgle88/sprint/sprint-page-contant';
import '../components/utilits/timer';
import '../components/fullscreen';
import '../components/utilits/random';
import '../components/constants';
